Added deposit revert and adjustment
rbkmoney/newway pull request #180
Opened 2021-02-16 08:16 UTC by inallyoung

2021-02-17 13:37 UTC, PospolitaNV requested changes

2021-02-17 13:37 UTC, PospolitaNV commented on src/main/java/com/rbkmoney/newway/poller/event_stock/impl/deposit/adjustment/DepositAdjustmentCreatedHandler.java
> +        depositAdjustment.setEventOccuredAt(TypeUtil.stringToLocalDateTime(timestampedChange.getOccuredAt()));
есть вынесенная функция жеж

2021-02-17 13:37 UTC, PospolitaNV commented on src/main/java/com/rbkmoney/newway/poller/event_stock/impl/deposit/revert/DepositRevertCreatedHandler.java
> +        depositRevert.setId(null);
Тоже

2021-02-17 13:37 UTC, PospolitaNV commented on src/main/java/com/rbkmoney/newway/poller/event_stock/impl/deposit/revert/DepositRevertCreatedHandler.java
> +        depositRevertDao.save(depositRevert).ifPresentOrElse(
Век живи - век учись, не знал про ifPresentOrElse, я обычно в 2 метода делаю )))

2021-02-17 13:37 UTC, PospolitaNV commented on src/test/java/com/rbkmoney/newway/dao/DepositAdjustmentDaoTest.java
> +    private DepositAdjustmentDao depositadjustmentDao;
глаза порезал ((

2021-02-17 13:37 UTC, PospolitaNV commented on src/test/java/com/rbkmoney/newway/dao/DepositAdjustmentDaoTest.java
> +        depositadjustmentDao.save(deposit);
есть вроде assertNotThrown()

2021-02-17 13:37 UTC, PospolitaNV commented on src/test/java/com/rbkmoney/newway/dao/DepositAdjustmentDaoTest.java
> +        jdbcTemplate.execute("truncate table nw.deposit_adjustment cascade");
кажется это лишнее, новая таблица.
Давай лучше @Transactional на класс повесим (чистка данных после теста)

2021-02-17 13:37 UTC, PospolitaNV commented on src/test/java/com/rbkmoney/newway/dao/DepositRevertDaoTest.java
> +    public void depositRevertTest() {
*те же комментарии*

2021-02-17 14:06 UTC, inallyoung commented on src/test/java/com/rbkmoney/newway/dao/DepositAdjustmentDaoTest.java
> +    private DepositAdjustmentDao depositadjustmentDao;
прости

2021-02-17 14:12 UTC, inallyoung commented on src/test/java/com/rbkmoney/newway/dao/DepositAdjustmentDaoTest.java
> +        depositadjustmentDao.save(deposit);
чет не нашел(

2021-02-18 08:39 UTC, PospolitaNV approved these changes

2021-02-18 10:12 UTC, merged