JD-380: new payouts
rbkmoney/newway pull request #197
Opened 2021-06-24 16:39 UTC by inallyoung

2021-06-24 16:56 UTC, karleowne commented on src/main/java/com/rbkmoney/newway/handler/event/stock/impl/payout/PayoutCreatedHandler.java
> +        com.rbkmoney.payout.manager.Payout payoutSource = change.getCreated().getPayout();
var

2021-06-24 22:09 UTC, inallyoung commented on src/main/java/com/rbkmoney/newway/handler/event/stock/impl/payout/PayoutCreatedHandler.java
> +        com.rbkmoney.payout.manager.Payout payoutSource = change.getCreated().getPayout();
![image](https://user-images.githubusercontent.com/22119973/123338694-f8e8b680-d551-11eb-8594-d79f86c391b7.png)

2021-06-25 05:40 UTC, karleowne approved these changes

2021-06-25 08:48 UTC, karleowne requested changes
https://github.com/rbkmoney/payout-manager-proto/pull/8

2021-06-25 12:20 UTC, karleowne approved these changes
разобрались с проколом

2021-07-09 07:19 UTC, karleowne approved these changes

2021-07-09 09:23 UTC, merged